### ISSUE TITLE
Dependencies resolved during project configuration

### ISSUE THREAD

**Issue by jkat-plumpop** [gigaSproule/swagger-gradle-plugin#139]
When I run a Gradle scan of my project with the Swagger plugin included, I am seeing an issue with dependencies being resolved during project configuration in the output.

```
Dependencies were resolved during project configuration

Dependency resolution during project configuration may reduce build speed by resolving dependencies unnecessarily.
        :compileClasspath
        :runtimeClasspath

Learn more about dependency management - https://docs.gradle.org/current/userguide/introduction_dependency_management.html
```

This can be reproduced by adding the following Groovy,

```
def afterEvaluation = false
gradle.projectsEvaluated {
    afterEvaluation = true
}

allprojects { project ->
    configurations.all { configuration ->
        configuration.incoming.beforeResolve {
            if (!afterEvaluation) {
                throw new Exception("Configuration $configuration.name of project $project.name is being resolved at configuration time.")
            }
        }
    }
}
```
adding the Swagger plugin to the project, and running the 'tasks' task.

```
gradlew tasks
```

**Comment by wakingrufus** [comment]
I think this is the culprit: https://github.com/gigaSproule/swagger-gradle-plugin/blob/6079dd2e94166e33072ed4f36c929c9b4871df7d/plugin/src/main/groovy/com/benjaminsproule/swagger/gradleplugin/classpath/ClassFinder.groovy#L93

**Comment by wakingrufus** [comment]
I am going to attempt to fix this. I want to make sure my solution works on all supported versions of gradle, but I noticed the tests currently only test against gradle 6.3. Is there guidance on which versions of gradle are currently supported by this plugin?
Thanks.

**Comment by wakingrufus** [comment]
Actually the real problem is here: https://github.com/gigaSproule/swagger-gradle-plugin/blob/6079dd2e94166e33072ed4f36c929c9b4871df7d/plugin/src/main/groovy/com/benjaminsproule/swagger/gradleplugin/GradleSwaggerPlugin.groovy#L65
where the Classfinder is invoked during configuration in order to set the inputFiles property.
`inputFiles` is never read directly, so I assume it is being used so that Gradle will know when this task needs to be rerun. I will looks at an alternative was to get the file list that does not involve resolving the dependencies.

**Comment by wakingrufus** [comment]
This is still not fixed. I still get `Cannot change dependencies of dependency configuration 'compileOnly' after it has been included in dependency resolution.` errors when using the latest version of this plugin
