### ISSUE TITLE
Get `ClassNotFoundException` after `gradle clean`

### ISSUE THREAD

**Issue by gigaSproule** [gigaSproule/swagger-gradle-plugin#4]
When performing `gradle clean` and then `gradle swagger` a `ClassNotFoundException` is thrown. If `gradle swagger` is then run again, it works fine.

When running `gradle clean swagger` there are no exceptions thrown.

**Comment by groboclown** [comment]
I've been seeing this issue, too.  If I run "gradle clean", then "gradle swagger", the failure occurs.  If I run "gradle clean" then "gradle clean swagger", the same issue occurs.

It looks like the issue is because the `ApiSourceExtension.groovy` tries to pull in the expected classes before they are compiled.  I'm not familiar with the underlying Maven plugin, but I'm guessing that if getValidClasses() built up the classpath and searched for the classes as late as possible, this error won't happen.

**Comment by gigaSproule** [comment]
I don't seem to get the exception anymore, but it's not creating the JSON file. I will have to spend more time looking into it.

**Comment by gigaSproule** [comment]
I'll rebuild and push tomorrow

**Comment by gigaSproule** [comment]
released as part of 0.0.8
