### ISSUE TITLE
ApiImplicitParam for body does not set correct schema ref

### ISSUE THREAD

**Issue by michalstawski** [gigaSproule/swagger-gradle-plugin#96]
ApiImplicitParam when used for the request body does not set correct schema ref. It takes the ref name from Endpoint class. I have following code:

```
(...)
class SchedulesHandler @Inject constructor() : Handler {
(...)
    @PUT
    @Path("/schedules/{colleagueId}/{storeId}")
    @ApiOperation(value = "Saves colleagues' schedules",
            nickname = "scheduleSave",
            response = String::class)
    @ApiImplicitParams(
            ApiImplicitParam(name = "colleagueId", value = "Colleague id", required = true, dataType = "string", paramType = "path"),
            ApiImplicitParam(name = "storeId", value = "Store id", required = true, dataType = "string", paramType = "path"),
            ApiImplicitParam(name = "body", required = true, dataType = "my.packagename.MyClassName", paramType = "body")
    )
```

And it generates following param definition:
```
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SchedulesHandler'
```

Instead of ```$ref: '#/definitions/MyClassName'``` it is ```$ref: '#/definitions/SchedulesHandler'```

**Comment by orfeonomia** [comment]
I can confirm that the above is true as I experience the problem, too.
The code is a Kotlin snippet, but it seems to follow the documentation closely:
https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X

**Comment by gigaSproule** [comment]
I'm currently on a long holiday and without a computer, so I'll take a look at it when I'm home.

**Comment by gigaSproule** [comment]
Just to ensure I'm writing a good replicatable test, what is your method signature?

**Comment by michalstawski** [comment]
This is a ratpack application, with following handler method signature:
```
void handle(ratpack.handling.ContextContext ctx)
```

**Comment by gigaSproule** [comment]
I've created a branch with some tests and they are passing, so not sure why you are getting a different outcome.

**Comment by gigaSproule** [comment]
Had a little dig through the code and noticed this:
```
try {
    cls = Class.forName(param.dataType())
} catch (ClassNotFoundException ignored) {
    cls = method.getDeclaringClass()
}
```

So it seems that if it can't find the class, it defaults to the declaring class (not sure that's the best fallback though).

**Comment by gigaSproule** [comment]
I've created a PR, so now the expected behaviour is to fail the build if the class cannot be found, as the reference won't be able to be created, etc.

**Comment by orfeonomia** [comment]
I wonder whether the problem was stated sufficiently clear way. Because of this I would try to show once again what is the case.

All my detailed description may seem boring so in short:
1. I am sure the expected class is available but it seems I get fallback value.
2. Using ApiImplicitParam.dataTypeClass doesn't change anything - it still gives a fallback value but the class should be visible to the plugin (since it is visible to a compiler).
3. I answer your question.
 

The code sample:
```
// some annotations here (Path, Api, Produces, Consumes)
class SchedulesHandler @Inject constructor() : Handler {  // 1
    ...

    // put-related annotations:
    @PUT
    ...
    @ApiImplicitParams(
            ...
            ApiImplicitParam(
                name = "body",
                required = true,
                dataType = "my.packagename.MyDtoClassName", // 2
                paramType = "body")
    )
    void handle(ratpack.handling.Context ctx) {    // 3
        ...
        // 4:
        ctx.parse(MyDtoClassName::class.java)
        ...
    }
```

1:
`SchedulesHandler` is a class that implements Ratpack Handler interface.

2:
`my.packagename.MyDtoClassName` is a DTO class. It defines PUT data format (so PUT should accept requests having a JSON that can be deserialized to the MyDtoClassName).

3:
The `handle (Context)` is a standard Ratpack method signature.
Each Ratpack handler implements this method.
`Context` is neither body type nor it is defined by us. It is rather a kind of state of processing for Ratpack.

4:
here is a call to Ratpack method that reads a request (the one attached to Ratpack context) as a given type.
We read it as MyDtoClassName as the request's body should be deserializable as the MyDtoClassName instance.
That's why we define dataType as my.packagename.MyDtoClassName :)


What I just showed is obviously much more clearer than it needs to be. But...
Unfortunately, whatever I would do I get this specification:

```
    "............." : {
      "put" : {
        ...,
        "parameters" : [
          ..., {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/SchedulesHandler"
          }
        } ],
        ...
      }
    },
  ...
  "definitions" : {
    ...
    "SchedulesHandler" : {
      "type" : "object"
    },
    ...
  }

```

i.e. **there is**:

```
"$ref" : "#/definitions/SchedulesHandler"
```

**instead of**:

```
"$ref" : "#/definitions/MyDtoClassName"
```

You have said the **fallback value** is the declaring class and the value is set when a declared class cannot be found by `Class.forName()`. And it seems I actually got the fallback value.
Now I wonder why.
If this is because the plugin can't find the class then I am confused. I am **100% sure the FQCN is good and that the compiled class is available both in the `build` directory (at an expected path) and in JAR file**.

The plugin can find the other classes I point using ApiOperation.response field very well (see below example) and the classes are in the same module, the same project, the same language (Kotlin) and they are defined the same way (`data class` (with annotations) inside so called `Kotlin file`; no additional language features).
So the only visible difference is string Fully Qualified Class Name in ApiImplicitParam vs static class object in ApiOperation.

```
@ApiOperation(value = "do sth",
    response = MyOtherDtoClassName::class)
override fun handle(ctx: Context) {
    ...
}
```

produces:

```
  ...
  "............" : {
    "get" : {
      ...,
      "responses" : {
        "200" : {
          "description" : "successful operation",
          "schema" : {
            "$ref" : "#/definitions/MyOtherDtoClassName"
          }
        },
        "404" : {
          "description" : "Not found"
        },
        "500" : {
          "description" : "Internal server error"
        }
      }
    }
  }
  ...
```

My **answer** to your question:

Failing the build seems reasonable in general as this gives some more safety to other existing teams and projects.
But in my particular case this forces me to remove the ApiImplicitParam entirely (as not doing this will stop my builds). And if I remove the annotation then naturally I don't benefit from it (whatever the solution is).
Obviously, if a feature doesn't work for me then it's safer for me to know it. That's why I would say "I accept your solution", although it solves not quite the problem I face.


**An additional observation**

There is also `ApiImplicitParam.dataTypeClass` field available and if I use it the result is the same (fallback `SchedulesHandler` value instead of `MyDtoClassName`).
In this approach there is no need to perform Class.forName() as the plugin gets a reference to the class.
Also, it is almost warranted the class is visible/available to the plugin.
Yet it still works (i.e. doesn't work) as before. 

```
// some annotations here (Path, Api, Produces, Consumes)
class SchedulesHandler @Inject constructor() : Handler {
    ...

    // put-related annotations:
    @PUT
    ...
    @ApiImplicitParams(
            ...
            ApiImplicitParam(
                name = "body",
                required = true,
                dataTypeClass = my.packagename.MyDtoClassName::class,
                paramType = "body")
    )
    void handle(ratpack.handling.Context ctx) {
        ...
        ctx.parse(MyDtoClassName::class.java)
        ...
    }
```

**Comment by orfeonomia** [comment]
I wonder whether the problem was stated sufficiently clear way. Because of this I would try to show once again what is the case.

All my detailed description may seem boring so in short:
1. I am sure the expected class is available but it seems I get fallback value.
2. Using ApiImplicitParam.dataTypeClass doesn't change anything - it still gives a fallback value but the class should be visible to the plugin (since it is visible to a compiler).
3. I answer your question.
 

The code sample:
```
// some annotations here (Path, Api, Produces, Consumes)
class SchedulesHandler @Inject constructor() : Handler {  // 1
    ...

    // put-related annotations:
    @PUT
    ...
    @ApiImplicitParams(
            ...
            ApiImplicitParam(
                name = "body",
                required = true,
                dataType = "my.packagename.MyDtoClassName", // 2
                paramType = "body")
    )
    void handle(ratpack.handling.Context ctx) {    // 3
        ...
        // 4:
        ctx.parse(MyDtoClassName::class.java)
        ...
    }
```

1:
`SchedulesHandler` is a class that implements Ratpack Handler interface.

2:
`my.packagename.MyDtoClassName` is a DTO class. It defines PUT data format (so PUT should accept requests having a JSON that can be deserialized to the MyDtoClassName).

3:
The `handle (Context)` is a standard Ratpack method signature.
Each Ratpack handler implements this method.
`Context` is neither body type nor it is defined by us. It is rather a kind of state of processing for Ratpack.

4:
here is a call to Ratpack method that reads a request (the one attached to Ratpack context) as a given type.
We read it as MyDtoClassName as the request's body should be deserializable as the MyDtoClassName instance.
That's why we define dataType as my.packagename.MyDtoClassName :)


What I just showed is obviously much more clearer than it needs to be. But...
Unfortunately, whatever I would do I get this specification:

```
    "............." : {
      "put" : {
        ...,
        "parameters" : [
          ..., {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/SchedulesHandler"
          }
        } ],
        ...
      }
    },
  ...
  "definitions" : {
    ...
    "SchedulesHandler" : {
      "type" : "object"
    },
    ...
  }

```

i.e. **there is**:

```
"$ref" : "#/definitions/SchedulesHandler"
```

**instead of**:

```
"$ref" : "#/definitions/MyDtoClassName"
```

You have said the **fallback value** is the declaring class and the value is set when a declared class cannot be found by `Class.forName()`. And it seems I actually got the fallback value.
Now I wonder why.
If this is because the plugin can't find the class then I am confused. I am **100% sure the FQCN is good and that the compiled class is available both in the `build` directory (at an expected path) and in JAR file**.

The plugin can find the other classes I point using ApiOperation.response field very well (see below example) and the classes are in the same module, the same project, the same language (Kotlin) and they are defined the same way (`data class` (with annotations) inside so called `Kotlin file`; no additional language features).
So the only visible difference is string Fully Qualified Class Name in ApiImplicitParam vs static class object in ApiOperation.

```
@ApiOperation(value = "do sth",
    response = MyOtherDtoClassName::class)
override fun handle(ctx: Context) {
    ...
}
```

produces:

```
  ...
  "............" : {
    "get" : {
      ...,
      "responses" : {
        "200" : {
          "description" : "successful operation",
          "schema" : {
            "$ref" : "#/definitions/MyOtherDtoClassName"
          }
        },
        "404" : {
          "description" : "Not found"
        },
        "500" : {
          "description" : "Internal server error"
        }
      }
    }
  }
  ...
```

My **answer** to your question:

Failing the build seems reasonable in general as this gives some more safety to other existing teams and projects.
But in my particular case this forces me to remove the ApiImplicitParam entirely (as not doing this will stop my builds). And if I remove the annotation then naturally I don't benefit from it (whatever the solution is).
Obviously, if a feature doesn't work for me then it's safer for me to know it. That's why I would say "I accept your solution", although it solves not quite the problem I face.


**An additional observation**

There is also `ApiImplicitParam.dataTypeClass` field available and if I use it the result is the same (fallback `SchedulesHandler` value instead of `MyDtoClassName`).
In this approach there is no need to perform Class.forName() as the plugin gets a reference to the class.
Also, it is almost warranted the class is visible/available to the plugin.
Yet it still works (i.e. doesn't work) as before. 

```
// some annotations here (Path, Api, Produces, Consumes)
class SchedulesHandler @Inject constructor() : Handler {
    ...

    // put-related annotations:
    @PUT
    ...
    @ApiImplicitParams(
            ...
            ApiImplicitParam(
                name = "body",
                required = true,
                dataTypeClass = my.packagename.MyDtoClassName::class,
                paramType = "body")
    )
    void handle(ratpack.handling.Context ctx) {
        ...
        ctx.parse(MyDtoClassName::class.java)
        ...
    }
```

**Comment by orfeonomia** [comment]
I have prepared a mini-project that reproduces the issue. Additionally, I have created a description for the project files and the detailed steps to reproduce the unwanted behavior.
I can send it via email if you agree (17kb.

**Comment by gigaSproule** [comment]
Should now be fixed

**Comment by orfeonomia** [comment]
thank you for the response. We will check this and come back with a feedback
